### ISSUE TITLE
Helm doesn't template when disabling postgresql

### ISSUE THREAD

**Issue by outofrange** [remram44/matrix-helm#3]
We want to use our own postgresql database instead of the "bundled" one (now bitnami/postgresql).

To do so, we set `postgresql.enabled = false`, and injected our own database secrets through the following construct:

```yaml
extraConfig:
- key: database.args.user
  secret:
    name: matrix-postgres-app
    key: user
- key: database.args.password
  secret:
    name: matrix-postgres-app
    key: password
- key: database.args.dbname
  secret:
    name: matrix-postgres-app
    key: dbname
- key: database.args.host
  secret:
    name: matrix-postgres-app
    key: host
```

A bit cumbersome, but this part should work.

What doesn't work is disabling postgresql (which we have to do, otherwise bitnami would overwrite our database credential if I'm not mistaken):

```
error: Error: template: matrix/templates/deployment.yaml:112:25: executing "matrix/templates/deployment.yaml" at <include "postgres.fullname" .Subcharts.postgres>: error calling include: template: no template "postgres.fullname" associated with template "gotpl"
```

The offending template is [this here](https://github.com/remram44/matrix-helm/blob/6ccfa8ab94793a7d2cd863ffe9418f4d2d477130/charts/matrix/templates/deployment.yaml#L112):

```yaml
          env:
            - name: PG_USER
              value: "{{ include "postgresql.v1.username" .Subcharts.postgresql }}"
            - name: PG_DB
              value: "{{ include "postgresql.v1.database" .Subcharts.postgresql }}"
            - name: PG_HOST
              value: "{{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}"
```

It seems like the chart tries to read template helpers from postgresql, even if the subchart is disabled and therefore not included.

Maybe I'm doing something wrong and there is a way simpler way of configuring a custom external DB, but I suspect that those env vars should be included conditionally depending on `postgresql.enabled`, like in other places.
