### ISSUE TITLE
Installing helm chart into non default namespace

### ISSUE THREAD

**Issue by mgabathuler** [remram44/matrix-helm#7]
I am trying to install the helm chart into a specific namespace. Creating the secret seems to fail as it is never created.

Looking at the code I suspect that the job is trying to create the secret in the namespace default.
https://github.com/remram44/matrix-helm/blob/affc3f2839bccfc3ce494f8182942cb8c1b6655e/charts/matrix/templates/job.yaml#L48

Creating the secret manually seems to help but starting the container fails with
```
OSError: [Errno 30] Read-only file system: '/etc/synapse/secret/signing.key'
Generating signing key file /etc/synapse/secret/signing.key
Stream closed EOF for ou-isg/matrix-server-86dd95d7f7-49s6b (matrix) 
```
which is expected.
How do I need to generate the signing key to include into my manually created secret?

This is the secret I create:
```
apiVersion: v1
kind: Secret
metadata:
  name: matrix-server-secret
type: Opaque
data:
  form_secret: <base64encodedvalue>
  macaroon_secret_key: <base64encodedvalue>
  registration_shared_secret: <base64encodedvalue>
```
